theme: jekyll-theme-minimal
title: New Wheels Data Analysis Using SQL
description: >
  <h3>Data Analysis Using SQL for New Wheels Manufacturer</h3>
  <p>
    <br>
    <br>
    <b>Libraries:</b>
    <ul>
      <li>SQL</li>
      <li>Microsoft Excel</li>
    </ul>
    <br>
  </p>
---
